[workspace]
members = [
    "app",
    "components",
    "config",
    "i18n",
    "macros",
    "simple-icons",
    "types",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.wasm-release]
inherits = "release"
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.dependencies]
simple-icons = { path = "./simple-icons" }
simple-icons-website-macros = { path = "./macros" }
simple-icons-website-i18n = { path = "./i18n" }
simple-icons-website-config = { path = "./config" }
simple-icons-website-types = { path = "./types" }
simple-icons-website-components = { path = "./components" }
leptos = { version = "0.5.4", default-features = false, features = [
    "csr",
    "nightly",
    "miniserde",
] }
leptos_meta = { version = "0.5.4", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos_router = { version = "0.5.4", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos-use = "0.9.0"
console_log = "1.0.0"
log = "0.4.20"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.66", default-features = false, features = [
    "Element",
    "HtmlDocument",
    "HtmlCollection",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "File",
    "FileList",
    "Blob",
    "DomTokenList",
    "EventTarget",
    "Storage",
    "Clipboard",
    "Event",
    "EventInit",
    "History",
    "Navigator",
    "MediaQueryList",
    "Request",
    "RequestInit",
    "RequestCache",
    "CanvasRenderingContext2d",
    "OffscreenCanvasRenderingContext2d",
] }
js-sys = "0.3.66"
wasm-bindgen-futures = "0.4.39"
lazy_static = "1.4.0"
syn = "2.0.42"
colorsys = "0.6.7"
serde_json = "1.0.108"
nanoserde = "0.1.35"
svg-path-cst = "0.0.7"
unicode-normalization = "0.1.22"
icu_collator = "1.4.0"
fluent-templates = "0.8.0"
unic-langid = "0.9.4"
config = { version = "0.13.4", features = ["json"] }
snafu = { version = "0.8.0", default_features = false }
