[workspace]
members = [
    "app",
    "components",
    "config",
    "i18n",
    "macros",
    "simple-icons",
    "scripts"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
simple-icons = { path = "./simple-icons" }
simple-icons-website-macros = { path = "./macros" }
simple-icons-website-i18n = { path = "./i18n" }
simple-icons-website-config = { path = "./config" }
leptos = { version = "0.2.5", default-features = false, features = ["csr"] }
leptos_meta = { version = "0.2.5", default-features = false, features = [
    "csr"
] }
leptos_router = { version = "0.2.5", default-features = false, features = [
    "csr"
] }
console_log = "1.0.0"
log = "0.4.17"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.84"
reqwasm = "0.5.0"
web-sys = { version = "0.3.61", default-features = false, features = [
    "Element",
    "HtmlCollection",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "DomTokenList",
    "EventTarget",
    "Storage",
    "Clipboard",
    "IntersectionObserver",
    "IntersectionObserverInit",
    "IntersectionObserverEntry",
    "Event",
    "EventInit",
    "History",
    "Navigator",
    "MediaQueryList",
] }
js-sys = "0.3.61"
wasm-bindgen-futures = "0.4.34"
lazy_static = "1.4.0"
rspolib = "0.0.5"
syn = "2.0.9"
colorsys = "0.6.7"
dotenv = "0.15.0"
serde_json = "1.0.94"
nanoserde = "0.1.32"
unicode-normalization = "0.1.22"
icu_collator = "1.1.0"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
tokio = { version = "1.26.0", default-features = false, features = [
    "macros",
    "rt-multi-thread"
] }
