[workspace]
members = ["app", "components", "config", "macros", "simple-icons", "types"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.wasm-release]
inherits = "release"
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.dependencies]
simple-icons = { path = "./simple-icons" }
simple-icons-website-macros = { path = "./macros" }
simple-icons-website-config = { path = "./config" }
simple-icons-website-types = { path = "./types" }
simple-icons-website-components = { path = "./components" }
leptos = { version = "0.6.12", default-features = false, features = [
    "csr",
    "nightly",
] }
leptos_meta = { version = "0.6.12", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos_router = { version = "0.6.12", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos-use = "0.10.10"
leptos-fluent = "0.0.34"
leptos_hotkeys = "0.2.1"
leptos_icons = "0.3.1"
icondata = "0.3.1"
console_log = "1"
log = "0.4.21"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", default-features = false, features = [
    "Blob",
    "DomTokenList",
    "CanvasRenderingContext2d",
    "Clipboard",
    "Element",
    "Event",
    "EventInit",
    "EventTarget",
    "File",
    "FileList",
    "History",
    "HtmlDocument",
    "HtmlCollection",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "Location",
    "MediaQueryList",
    "Navigator",
    "OffscreenCanvasRenderingContext2d",
    "Storage",
    "Request",
    "RequestInit",
    "RequestCache",
    "Url",
    "UrlSearchParams",
] }
js-sys = "0.3.69"
wasm-bindgen-futures = "0.4.42"
lazy_static = "1.4.0"
syn = "2.0.66"
colorsys = "0.6.7"
serde_json = "1.0.117"
nanoserde = "0.1.37"
svg-path-cst = "0.1.0"
unicode-normalization = "0.1.23"
icu_collator = "1.5.0"
fluent-templates = "0.9"
config = { version = "0.14.0", features = ["json"] }
snafu = { version = "0.8.3", default-features = false }
rand = "0.8.5"
