[workspace]
members = ["app", "components", "config", "macros", "simple-icons", "types"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.wasm-release]
inherits = "release"
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.dependencies]
simple-icons = { path = "./simple-icons" }
simple-icons-website-macros = { path = "./macros" }
simple-icons-website-config = { path = "./config" }
simple-icons-website-types = { path = "./types" }
simple-icons-website-components = { path = "./components" }
leptos = { version = "0.6.13", default-features = false, features = [
    "csr",
    "nightly",
] }
leptos_meta = { version = "0.6.13", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos_router = { version = "0.6.13", default-features = false, features = [
    "csr",
    "nightly"
] }
leptos-use = "0.10"
leptos-fluent = { version = "0.1", default-features = false, features = [
    "nightly"
] }
fluent-templates = "0.9"
leptos_hotkeys = "0.2.1"
leptos_icons = "0.3"
icondata = { version = "0.4", default-features = false, features = [
    "simple-icons",
    "charm",
    "tabler-icons",
    "lucide",
    "remix-icon",
    "ionicons",
    "font-awesome",
    "box-icons",
    "bootstrap-icons",
    "vs-code-icons",
] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3", default-features = false, features = [
    "Blob",
    "DomTokenList",
    "CanvasRenderingContext2d",
    "Clipboard",
    "Element",
    "Event",
    "EventInit",
    "EventTarget",
    "File",
    "FileList",
    "History",
    "HtmlDocument",
    "HtmlCollection",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "Location",
    "MediaQueryList",
    "Navigator",
    "OffscreenCanvasRenderingContext2d",
    "Storage",
    "Request",
    "RequestInit",
    "RequestCache",
    "Url",
    "UrlSearchParams",
] }
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
lazy_static = "1.4"
syn = "2.0"
colorsys = "0.6"
serde_json = "1"
nanoserde = "0.1"
svg-path-cst = "0.1"
unicode-normalization = "0.1"
icu_collator = "1"
config = { version = "0.14", features = ["json"] }
snafu = { version = "0.8", default-features = false }
rand = "0.8"
