[package]
name = "simple-icons-website-config"
description = "Simple Icons website configuration"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
name = "simple_icons_website_config"

[dependencies]
config.workspace = true
lazy_static.workspace = true
