name: Verify
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  run:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test${{ github.ref == 'refs/heads/master' && ' and deploy' || '' }}
            cargo-make-command: tests
          - name: Lint
            cargo-make-command: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup default nightly
          rustup target add wasm32-unknown-unknown
      - name: Install tooling dependencies
        run: cargo install cargo-make
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-nightly
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js dependencies
        run: npm ci
      - name: Install Playwright browsers
        if: matrix.cargo-make-command == 'tests'
        run: npx playwright install --with-deps
      - name: Build for testing
        if: matrix.cargo-make-command == 'tests'
        run: cargo make builds
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: 'true'
      - name: Run `cargo make ${{ matrix.cargo-make-command }}`
        run: cargo make ${{ matrix.cargo-make-command }}
      - name: Upload test results
        if: matrix.cargo-make-command == 'tests'
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
