name: Get Rust toolchain configuration

on:
  workflow_call:
    outputs:
      rust-version:
        description: Rust version
        value: ${{ jobs.get-toolchain-config.outputs.rust-version }}

jobs:
  get-toolchain-config:
    name: Get toolchain configuration
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.toolchain.outputs.rust-version }}
    steps:
      - id: toolchain
        name: Get toolchain configuration
        run: |
          echo "rust-version=$(grep channel -i rust-toolchain.toml | cut -d '"' -f2)" \
            >> $GITHUB_OUTPUT
